default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: download_upload_file
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  #schema_search_path: myapp,sharedapp,public.
  #min_messages: notice

test:
  <<: *default
  database: download_upload_file_test

production:
  <<: *default
  database: download_upload_file_production
  username: download_upload_file
  password: <%= ENV['DOWNLOAD_UPLOAD_FILE_DATABASE_PASSWORD'] %>
